# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 00:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import utility.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('event', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('files', django.contrib.postgres.fields.jsonb.JSONField(default=list, validators=[utility.validator.ListValidator(code='invalid', message='Value should be a list of dictionary.')])),
                ('author', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='channel.Channel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='account.User')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
