# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 00:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import utility.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('designer', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('schemes', django.contrib.postgres.fields.jsonb.JSONField(default=list, validators=[utility.validator.ListValidator(code='invalid', message='Value should be a list of dictionary.')])),
                ('specsheets', django.contrib.postgres.fields.jsonb.JSONField(default=list, validators=[utility.validator.ListValidator(code='invalid', message='Value should be a list of dictionary.')])),
                ('samples', django.contrib.postgres.fields.jsonb.JSONField(default=list, validators=[utility.validator.ListValidator(code='invalid', message='Value should be a list of dictionary.')])),
                ('renderings', django.contrib.postgres.fields.jsonb.JSONField(default=list, validators=[utility.validator.ListValidator(code='invalid', message='Value should be a list of dictionary.')])),
                ('blueprints', django.contrib.postgres.fields.jsonb.JSONField(default=list, validators=[utility.validator.ListValidator(code='invalid', message='Value should be a list of dictionary.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prototypes', to='account.User')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
