# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 00:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dialogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('channel', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('ipv4', models.GenericIPAddressField(protocol='IPv4')),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='dialogue.Dialogue')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
