# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-11 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180111_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_std_auth_enabled',
        ),
        migrations.AddField(
            model_name='user',
            name='is_oauth_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
